#ifndef BOARD_SPOTPEAR_LCD_1_9_H
#define BOARD_SPOTPEAR_LCD_1_9_H

/* SEN54 I2C */
#define BOARD_SEN54_I2C_PORT 0
#define BOARD_SEN54_I2C_SDA_PIN 42
#define BOARD_SEN54_I2C_SCL_PIN 45

/* LCD (ST7789 on Spotpear 1.9 inch) */
#define BOARD_LCD_SPI_HOST SPI2_HOST
#define BOARD_LCD_PIN_NUM_MOSI 13
#define BOARD_LCD_PIN_NUM_CLK 10
#define BOARD_LCD_PIN_NUM_CS 12
#define BOARD_LCD_PIN_NUM_DC 11
#define BOARD_LCD_PIN_NUM_RST 9
#define BOARD_LCD_PIN_NUM_BK_LIGHT (-1)

/* Touch controller */
#define BOARD_TOUCH_I2C_PORT 1
#define BOARD_TOUCH_I2C_SDA_PIN 47
#define BOARD_TOUCH_I2C_SCL_PIN 48
#define BOARD_TOUCH_I2C_ADDR 0x15

/* RS485 transceiver */
#define BOARD_RS485_UART_PORT UART_NUM_2
#define BOARD_RS485_UART_TX_PIN GPIO_NUM_17
#define BOARD_RS485_UART_RX_PIN GPIO_NUM_16
#define BOARD_RS485_UART_DE_RE_PIN GPIO_NUM_5

/* PMS5003 (onboard peripheral) */
#define BOARD_PMS5003_UART_NUM UART_NUM_1
#define BOARD_PMS5003_RX_PIN 5
#define BOARD_PMS5003_TX_PIN 4
#define BOARD_PMS5003_SET_PIN 6

#endif /* BOARD_SPOTPEAR_LCD_1_9_H */
