#ifndef UI_PROFILE_SEN54_320X170_H
#define UI_PROFILE_SEN54_320X170_H

/* Profile identity */
#define UI_PROFILE_NAME "SEN54_320X170"

/* Expected UI canvas */
#define UI_PROFILE_EXPECTED_DISPLAY_WIDTH 320
#define UI_PROFILE_EXPECTED_DISPLAY_HEIGHT 170

/* Touch policy */
#define UI_PROFILE_TOUCH_REQUIRED 0

/* Screen availability */
#define UI_PROFILE_ENABLE_SCREEN_MAIN_MEASUREMENTS 1
#define UI_PROFILE_ENABLE_SCREEN_SEN54_CONTROLS 1
#define UI_PROFILE_ENABLE_SCREEN_SEN54_DIAGNOSTICS 1

#endif /* UI_PROFILE_SEN54_320X170_H */
